export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  position: number;
  isVisible: boolean;
  stock: number;
  isPreOrder: boolean;
  deliveryDate?: string;
  kautionAmount: number;
  subscription3YearPrice?: number;
  subscription5YearPrice?: number;
}

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Nordic Water Carafe",
    description: "Hand-blown borosilicate glass carafe with a minimalist silhouette. Perfect for serving water or wine with understated elegance.",
    price: 49.00,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=600&fit=crop",
    category: "Tableware",
    position: 0,
    isVisible: true,
    stock: 12,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-2",
    name: "Oak Serving Board",
    description: "Solid FSC-certified oak serving board with natural grain patterns. Finished with food-safe mineral oil.",
    price: 65.00,
    image: "https://images.unsplash.com/photo-1603199506016-b9a594b593c0?w=600&h=600&fit=crop",
    category: "Kitchen",
    position: 1,
    isVisible: true,
    stock: 8,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-3",
    name: "Linen Napkin Set",
    description: "Set of 4 stonewashed linen napkins in warm natural tone. Softens with every wash.",
    price: 38.00,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop",
    category: "Textiles",
    position: 2,
    isVisible: true,
    stock: 24,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-4",
    name: "Ceramic Pour-Over Set",
    description: "Matte ceramic pour-over coffee dripper with matching server. Designed for the ritual of slow coffee.",
    price: 82.00,
    image: "https://images.unsplash.com/photo-1517080319261-425b32e1db33?w=600&h=600&fit=crop",
    category: "Kitchen",
    position: 3,
    isVisible: true,
    stock: 6,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-5",
    name: "Wool Throw Blanket",
    description: "100% merino wool throw in soft grey. Lightweight yet warm, with a subtle herringbone weave.",
    price: 120.00,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&h=600&fit=crop",
    category: "Textiles",
    position: 4,
    isVisible: true,
    stock: 5,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-6",
    name: "Concrete Candle Holder",
    description: "Hand-poured concrete candle holder with a raw, tactile surface. Fits standard pillar candles.",
    price: 28.00,
    image: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&h=600&fit=crop",
    category: "Decor",
    position: 5,
    isVisible: true,
    stock: 18,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-7",
    name: "Stoneware Bowl Set",
    description: "Set of 3 nested stoneware bowls with a reactive glaze finish. Microwave and dishwasher safe.",
    price: 56.00,
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&h=600&fit=crop",
    category: "Tableware",
    position: 6,
    isVisible: true,
    stock: 10,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-8",
    name: "Brass Desk Lamp",
    description: "Minimalist brass desk lamp with an adjustable arm and warm LED bulb. Dimmable touch control.",
    price: 145.00,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop",
    category: "Lighting",
    position: 7,
    isVisible: true,
    stock: 4,
    isPreOrder: false,
    kautionAmount: 0,
  },
  {
    id: "prod-9",
    name: "Smart Home Water Filter",
    description: "Advanced ceramic filtration system with IoT connectivity. Monitors water quality in real-time. Pre-order now for Q1 2026 delivery.",
    price: 299.00,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop",
    category: "Appliances",
    position: 8,
    isVisible: true,
    stock: 0,
    isPreOrder: true,
    deliveryDate: "2026-03-15",
    kautionAmount: 49.00,
    subscription3YearPrice: 12.50,
    subscription5YearPrice: 9.90,
  },
  {
    id: "prod-10",
    name: "Modular Storage System",
    description: "Scandinavian-inspired modular shelving with sustainable bamboo construction. Configure to fit any space. Pre-order for custom delivery.",
    price: 450.00,
    image: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&h=600&fit=crop",
    category: "Furniture",
    position: 9,
    isVisible: true,
    stock: 0,
    isPreOrder: true,
    deliveryDate: "2026-04-01",
    kautionAmount: 89.00,
    subscription3YearPrice: 18.75,
    subscription5YearPrice: 14.90,
  },
];
